# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://poppytime.website
title: Poppy Time
email: poppytime@torharrington.com
author: Tor Harrington
description: > # "Poppy Time is a Pebble Watchface designed specifically for the
  Pebble Time, Pebble Time Steel and Pebble Time Round series of Smartwatches. Show
  support during Remembrance Day with a digital Poppy on your wrist. Please don't
  forget to donate and support fallen comdrades and loved ones everywhere.
copyright: 'Copyright &copy; 2016 Tor Harrington. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Jekyll theme created by <a href="https://github.com/swcool/landing-page-theme/">Shane Weng</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

social:
  - icon: twitter
    url: http://www.twitter.com/torharrington
  - icon: github
    url: http://www.github.com/torharrington
  - icon: slack
    url: http://pebbledev.slack.com
  - icon: google-plus
    url: https://plus.google.com/+torharrington
  - icon: envelope-o
    url: mailto:info@poppytime.website
